require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# https://github.com/facebook/react-native/pull/36759
# Force pods to match minimum iOS version for React Native
# Fixes build issue on Xcode Cloud where some pods
# Use iOS 12 calls despite being set as iOS 11
def __apply_Xcode_14_3_RC_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      minimum_target = min_ios_version_supported
      if current_target.to_f < minimum_target.to_f
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_target
      end
    end
  end
end

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


target 'app' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'appTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    __apply_Xcode_14_3_RC_post_install_workaround(installer)

    # Xcode 26's clang reports Yoga's `operator"" _pt` spelling as
    # -Wdeprecated-literal-operator, which Yoga.podspec's -Werror makes fatal.
    # Keep it a warning (no codegen change).
    installer.pods_project.targets.each do |target|
      next unless target.name == 'Yoga'
      target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = '$(inherited) -Wno-error=deprecated-literal-operator'
      end
    end

    # Boost 1.76 (container_hash) uses std::unary_function, which current libc++
    # removes in C++17 mode. Re-enable it with libc++'s documented macro.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        defs = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        defs = [defs] unless defs.is_a?(Array)
        defs << '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION' unless defs.include?('_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION')
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
      end
    end

    # App Store Connect rejects executables that contain bitcode (ITMS-90482);
    # React Native 0.71's prebuilt Hermes framework contains it. Strip it from
    # the downloaded binaries with Apple's bitcode_strip, failing if none is found.
    hermes_bins = Dir.glob(File.join(installer.sandbox.root, 'hermes-engine', '**', 'hermes.framework', '**', 'hermes'))
                     .select { |f| File.file?(f) }.map { |f| File.realpath(f) }.uniq
    raise 'hermes.framework binaries not found' if hermes_bins.empty?
    hermes_bins.each do |bin|
      system('xcrun', 'bitcode_strip', '-r', bin, '-o', bin) || raise("bitcode_strip failed: #{bin}")
    end
  end
end